services:
  postgres:
    image: postgres:17
    container_name: duck-store-postgres

    environment:
      POSTGRES_DB: duck_store
      POSTGRES_USER: duckstore
      POSTGRES_PASSWORD: duckstore

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: