CREATE TABLE ducks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    color VARCHAR(20) NOT NULL,

    size VARCHAR(20) NOT NULL,

    price NUMERIC(12, 2) NOT NULL,

    quantity INTEGER NOT NULL,

    deleted BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT chk_ducks_color
        CHECK (color IN ('RED', 'GREEN', 'YELLOW', 'BLACK')),

    CONSTRAINT chk_ducks_size
        CHECK (size IN ('XLARGE', 'LARGE', 'MEDIUM', 'SMALL', 'XSMALL')),

    CONSTRAINT chk_ducks_price
        CHECK (price > 0),

    CONSTRAINT chk_ducks_quantity
        CHECK (quantity >= 0)
);

CREATE UNIQUE INDEX ux_ducks_active_color_size_price
ON ducks(color, size, price)
WHERE deleted = FALSE;